googlemaps/v3-utility-library

markerwithlabel/src/markerwithlabel.js
You can't use css hover because you are hovering the "invisible" div and if you try change color or anything else you won't see it because 0.1 opacity.
You must choose between to hover labels by css or to capture events even if the label is in the shadow of a google.maps.InfoWindow.
More info about the problem [here](https://github.com/angular-ui/angular-google-maps/issues/1574#issuecomment-149764981)
=> Markers with label are now css hoverable

markerclusterer/src/markerclusterer.js
Replaced the copy pasta with corrected comments.
=> Incorrect Comments

markerclusterer/examples/advanced_example.html, markerclustererplus/examples/advanced_example.html, markerclustererplus/examples/events_example.html, markerclustererplus/examples/simple_example.html, markerclustererplus/examples/speed_test_example.html
=> Change some marker clusterer example urls to use https for issue #389

markerclusterer/docs/reference.html
as #23 `getTotalMarkers()` returns number.
=> fix return value and description

packages/markerclusterer/package.json, packages/markerclustererplus/package.json, packages/markerwithlabel/package.json
=> add src and dist to files in package config

packages/markerclusterer/package.json, packages/markerclusterer/src/markerclusterer.js, packages/markerclustererplus/package.json, packages/markerclustererplus/src/markerclusterer.js, packages/markerwithlabel/src/markerwithlabel.js
- remove embedded version from packages
- fix version tag in publish config
=> fix version issues

.travis.yml, package.json
see https://codecov.io/gh/googlemaps/v3-utility-library/branch/feat%2Fconverage
=> enable code coverage reporting to codecov

.travis.yml, package.json, packages/ogc/CONTRIB.md, packages/ogc/README.md, packages/ogc/examples/wmslayer.html, packages/ogc/jest.config.js, packages/ogc/package.json, packages/ogc/rollup.config.js, packages/ogc/src/index.ts, packages/ogc/src/wmslayer.ts, packages/ogc/src/wmslayers.test.ts, packages/ogc/tsconfig.json, packages/ogc/tsconfig.lint.json
This is adds a plugin for WMS layers to be added to google maps.
=> add ogc plugin with wmslayer

packages/markerclustererplus/src/markerclusterer.js
=> fix missing plus to concat tabindex

packages/markerwithlabel/src/markerwithlabel.js
Improve code for when position resolves as undefined
=> Update marker with label: Improve error handling of position

packages/markerclusterer/src/markerclusterer.js
relating to issue https://github.com/googlemaps/v3-utility-library/issues/582
=> Fix doc styles prop on MarketClusterer

packages/markerclustererplus/package.json
=> fix(@google/markerclustererplus): remove src/* from npm

.gitignore, package-lock.json
=> build: add package lock

packages/markerclustererplus/examples/advanced_example.html, packages/markerclustererplus/src/cluster-icon.ts, packages/markerclustererplus/src/markerclusterer.ts
Closing https://github.com/googlemaps/v3-utility-library/issues/589
=> feat(markerclustererplus): add `className` property for ClusterIconStyle

packages/loader/package.json, packages/markerclusterer/package.json, packages/markerclustererplus/package.json, packages/markermanager/package.json, packages/ogc/package.json
=> fix: set browserslist setting for babel

.babelrc, package-lock.json, package.json, packages/loader/.babelrc, packages/loader/package.json, packages/loader/rollup.config.js, packages/markerclusterer/.babelrc, packages/markerclusterer/package.json, packages/markerclusterer/rollup.config.js, packages/markerclustererplus/.babelrc, packages/markerclustererplus/package.json, packages/markerclustererplus/rollup.config.js, packages/markermanager/.babelrc, packages/markermanager/package.json, packages/markermanager/rollup.config.js, packages/ogc/.babelrc, packages/ogc/package.json, packages/ogc/rollup.config.js
=> fix: add polyfills via core-js

packages/loader/src/index.ts
Thank you for opening a Pull Request!
---
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
=> fix: adds LoaderOptions export

packages/loader/README.md
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
=> docs(@googlemaps/loader): add note to use @googlemaps/js-api-loader

packages/markerclustererplus/src/overlay-view-safe.ts
=> fix: use let instead of const in for loop

packages/markerclustererplus/examples/advanced_example.html, packages/markerclustererplus/rollup.config.js, packages/markerclustererplus/src/markerclusterer.ts
=> feat: add padding for fitMapToMarkers

packages/jest-mocks/src/index.ts, packages/jest-mocks/src/mvcarray.ts, packages/jest-mocks/src/polyline.ts
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
I added news mocks to jest-mocks. 
One for MVCArray.
Another for Polyline. 
And i replicate the enum MapTypeId. 
I hope you like :)
=> feat(jest-mocks): create enum MapTypeId. Create class MVCArray and Polyline
