googlemaps/v3-utility-library

markerwithlabel/src/markerwithlabel.js

* Added label element to the markerLayer instead of the overlayImage.
It looks like the marker and label elements were created on separate layers, which makes it impossible to set zIndex values which would cause the labels to appear underneath the markers. Appending the label elements to the same layer as the marker elements fixes this problem.
However, I'm not entirely sure if this is a good solution. Maybe there's a reason the labels were added to a separate layer to the markers.

Fix for #326

---

infobox/src/infobox.js

This makes InfoBox work better with MarkerClusterer, hiding and showing boxes together with markers.

Hiding boxes for clustered markers

---

infobubble/src/infobubble.js

Allows infobubble usage on https websites without mixed content warnings
Closes #184 and https://code.google.com/p/google-maps-utility-library-v3/issues/detail?id=184

Load infobubble close button over https

---

infobox/examples/infobox-basic.html
infobox/examples/infobox-label.html

Prevent Mixed Content error on [basic](https://htmlpreview.github.io/?https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/infobox/examples/infobox-basic.html) and [label](https://htmlpreview.github.io/?https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/infobox/examples/infobox-label.html) infobox example pages.

load map and close btn in infobox example over https

---

markerclusterer/src/markerclusterer.js

This particular problem comes from the pattern
markerClusterer.removeMarkers( markerClusterer.getMarkers() ) as the
underlying mechanism to remove markers performs a splice on the same array
that the remove markers method is working against. This creates a local
copy of the passed in markers array so the above usage pattern works.

Fix for `removeMarkers` doesn't remove all markers #360

---

markerclusterer/src/markerclusterer.js
markerclustererplus/src/markerclusterer.js

If we have unclustered markers showing close enough to a cluster, clicking on the cluster executes the underlying marker's click handler because of marker's zIndex

fix issue with cluster clicks and unclustered markers

---

markerwithlabel/src/markerwithlabel.js

This fixes #412 by keeping track of the latest content used in the marker and comparing against it when using the `setContent` method to avoid unnecessary updates.

Update the content of the marker only if it has changed.

---

README.md
markerclusterer/README.md

The READMEs currently link to a seemingly outdated set of docs that don't include a list of what the options are that you can use with the MarkerClusterer constructor.

update link in README for MarkerClusterer docs

---

markerclusterer/src/markerclusterer.js

Fixes the bug when map is sometimes doesn't proper recenter. 
Center map to the the bounds of all markers inside a cluster.

Update markerclusterer.js: recentering the map after click on cluster

---

markerclusterer/src/markerclusterer.js

`window` may be set to `{}`. ([markerclusterer.js#L1264](https://github.com/ipcjs/v3-utility-library/blob/f38c127ab0d65b01cc26c317cdf39da5975bac79/markerclusterer/src/markerclusterer.js#L1264))

Prevent error: `window.setTimeout is not a function`

---

packages/markerclustererplus/src/markerclusterer.js

For one of the projects I've been working on lately, we wanted to make sure our map marker implementation was interactable for A11Y. Part of this required us to make changes to this file. However, I did not realize the file was copy-pasted from upstream. So I'm hoping to mainline this change and change what we need to in order to make this upstreaming possible.
The following PR makes the following changes:
- Adds tabindexes to the map markers
- Allows the consumer to add an aria label into the map marker based on a function that's passed in
Again, I developed this solution without a broader understanding of this library, please let me know what changes I can make on the design side if there are any to help get this functionality in

Added aria label support to markers via optional fn

---

packages/markerclustererplus/src/markerclusterer.js

TypeScript 3.7 is finally enabling `emitDeclarationOnly` and `allowJs` to be used together to generate typing files based off of JSDoc comments. This PR changes some of the JSDoc comments to output a much more clean typing file by using the TypeScript compiler on TS3.7

Change JSDoc so that TS3.7 can generate better typings

---

package.json
packages/markerclustererplus/package.json
packages/markerclustererplus/rollup.config.js
packages/markerclustererplus/tsconfig.json

Per TS3.7 updates (and enabled by #552), we're now able to generate a `.d.ts` file from the JSDoc comments. This PR adds in typings to the Markerclustererplus distributed package

Added typing generation to Markerclustererplus

---

packages/markerclusterer/src/markerclusterer.js
packages/markerclustererplus/src/markerclusterer.js

#403 
The value of `zIndex` should be left to the caller to control.

add `zIndex` option.

---

packages/markerclusterer/README.md
packages/markerclustererplus/README.md
packages/markermanager/README.md
packages/markerwithlabel/README.md

see #571 #572 #573 for using typedoc
closes #570

fix: remove old documentation links

---

packages/markerclusterer/src/markerclusterer.js
packages/markerclustererplus/src/markerclusterer.js

This bug was introduced in #569.

Fix typo when getting z-index from MarkerClusterer

---

package.json

@types/googlemaps 3.38.1 has `google.maps.version` needed for #590. thanks @bamnet

chore: update dev dependencies

---

packages/markerclustererplus/src/cluster.ts
packages/markerclustererplus/src/markerclusterer.ts

Fixes https://github.com/googlemaps/v3-utility-library/issues/605

fix(markerclustererplus): re-render icons on end of clustering cycle

---

packages/markerclustererplus/CHANGELOG.md

Link markerclustererplus `advanced_example.html`

docs: changelog fix formatting and link example

---

packages/jest-mocks/src/map.ts

Thank you for opening a Pull Request!
---
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #680

fix: missing `getClickableIcons` in class `_Map` [@googlemaps/jest-mocks]
